# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
- main

pool:
  vmImage: macOS-11

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.1'
  displayName: 'Install Node'
- script: npm install
  displayName: 'Install dependencies'
