# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/ci-cd
# TODO
# - develop
# - main

pool:
  vmImage: macOS-11

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '15.5.1'
  displayName: 'Install Node'
- script: npm cache verify
  displayName: 'Verify cache'
- script: npm install
  displayName: 'Install dependencies'
- script: npm run lint
  displayName: 'Run lint'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: AppleDeveloperCertificate.p12
    certPwd: $(P12_PASSWORD)
    keychain: 'temp'
    deleteCert: true
  displayName: Install Apple Certificate
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Amsterdamappprovisioningprofile.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'
- task: CocoaPods@0
  inputs:
    workingDirectory: './ios'
    forceRepoUpdate: true
- task: DownloadSecureFile@1
  displayName: 'Download App Store Connect API Key'
  name: AppStoreConnectApiKey
  inputs:
    secureFile: 'App_Store_Connect_API_Key_4B3KZ8N747.p8'
- task: DownloadSecureFile@1
  displayName: 'Download Play Store API Key'
  name: PlayStoreApiKey
  inputs:
    secureFile: 'api-5152920179310760437-158079-bad988ebb867.json'
- task: DownloadSecureFile@1
  displayName: 'Download Keystore'
  name: Keystore
  inputs:
    secureFile: 'upload-keystore'
- script: |
    cd ios
    cp $(AppStoreConnectApiKey.secureFilePath) .
    bundle install
    fastlane beta
  displayName: 'Build iOS'
- script: |
    cd android
    cp $(PlayStoreApiKey.secureFilePath) .
    cp $(Keystore.secureFilePath) .
    bundle install
    fastlane bump_version_code
    fastlane beta
  displayName: 'Build Android'
  
variables:
- group: React Native Variables
- name: lc.all
  value: 'en_US.UTF-8'
- name: lang
  value: 'en_US.UTF-8'
