# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/ci-cd
# TODO
# - develop
# - main

pool:
  vmImage: macOS-11

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.1'
  displayName: 'Install Node'
- script: npm install
  displayName: 'Install dependencies'
- script: npm run lint
  displayName: 'Run lint'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: AppleDeveloperCertificate.p12
    certPwd: $(P12password)
    keychain: 'temp'
    deleteCert: true
  displayName: Install Apple Certificate
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'AppleProvisioningProfile.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'
- script: |
    cd ios
    bundle install
    fastlane beta
  displayName: 'Build iOS'
  
variables:
- group: React Native Variables
