export enum ModuleSlug {
  'access-code' = 'access-code',
  address = 'address',
  chat = 'chat',
  'city-pass' = 'city-pass',
  'construction-work' = 'construction-work',
  'construction-work-editor' = 'construction-work-editor',
  'contact' = 'contact',
  elections = 'elections',
  home = 'home',
  'mijn-amsterdam' = 'mijn-amsterdam',
  'notification-history' = 'notification-history',
  onboarding = 'onboarding',
  parking = 'parking',
  redirects = 'redirects',
  'report-problem' = 'report-problem',
  survey = 'survey',
  user = 'user',
  'waste-container' = 'waste-container',
  'waste-guide' = 'waste-guide',
}
