export enum ModuleSlug {
  about = 'about',
  address = 'address',
  chat = 'chat',
  'city-pass' = 'city-pass',
  'construction-work' = 'construction-work',
  'construction-work-editor' = 'construction-work-editor',
  'contact' = 'contact',
  home = 'home',
  onboarding = 'onboarding',
  'open-waste-container' = 'open-waste-container',
  redirects = 'redirects',
  'report-problem' = 'report-problem',
  user = 'user',
  'waste-guide' = 'waste-guide',
}
