export enum ReduxKey {
  accessCode = 'accessCode',
  address = 'address',
  alert = 'alert',
  bottomSheet = 'bottomSheet',
  burningGuide = 'burningGuide',
  chat = 'chat',
  cityPass = 'cityPass',
  constructionWork = 'constructionWork',
  constructionWorkEditor = 'constructionWorkEditor',
  contact = 'contact',
  elections = 'elections',
  environment = 'environment',
  internetConnection = 'internetConnection',
  menu = 'menu',
  messageDraft = 'messageDraft',
  modules = 'modules',
  onboarding = 'onboarding',
  parking = 'parking',
  permissions = 'permissions',
  productTour = 'productTour',
  screen = 'screen',
  secureStorage = 'secureStorage',
  survey = 'survey',
  theme = 'theme',
  updateApp = 'updateApp',
  wasteGuide = 'wasteGuide',
}
