export enum ReduxKey {
  address = 'address',
  alert = 'alert',
  bottomSheet = 'bottomSheet',
  cityPass = 'cityPass',
  constructionWork = 'constructionWork',
  constructionWorkEditor = 'constructionWorkEditor',
  contact = 'contact',
  environment = 'environment',
  internet = 'internet',
  messageDraft = 'messageDraft',
  modules = 'modules',
  onboarding = 'onboarding',
  permissions = 'permissions',
  productTour = 'productTour',
  theme = 'theme',
  updateApp = 'updateApp',
  wasteGuide = 'wasteGuide',
}
