jobs:
  - job: 'Tests'
    timeoutInMinutes: 30
    pool:
      vmImage: macos-14
    steps:
      - template: ./install-node.yml
      - script: npm ci
        displayName: Install Dependencies
      - template: ./checks.yml
