require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

project 'AmsterdamApp',
        'Debug' => :debug,
        'DevDebug' => :debug,
        'Release' => :release,
        'DevRelease' => :release

target 'AmsterdamApp' do
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  target 'AmsterdamAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!(configurations: ['Debug', 'DevDebug'])

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    apply_flipper_fix(installer) 
  end
end
# Fix for https://github.com/facebook/react-native/issues/34332
def apply_flipper_fix(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'React-Core'
      target.build_configurations.each do |config|
        if config.debug?
          puts "Enabling Flipper for build configuration '#{config.name}'"
          # For 0.68.2. Note that main branch now uses GCC_PREPROCESSOR_DEFINITIONS: 
          # https://github.com/cipolleschi/react-native/blob/f3db6cc52792e3006a16408df4ae40f3aee19a86/scripts/cocoapods/flipper.rb#L87
          config.build_settings['OTHER_CFLAGS'] = "$(inherited) -DFB_SONARKIT_ENABLED=1"
        end
      end
    end
  end
end