trigger: 
  - main

pr: none

jobs:
  - job: "Build_Android"
    timeoutInMinutes: 90
    pool:
      vmImage: macOS-12
    variables:
      - group: React Native Variables
      - group: React Native Piwik Pro Analytics
      - group: device-authorization
      - name: lc.all
        value: 'en_US.UTF-8'
      - name: lang
        value: 'en_US.UTF-8'
    steps:
      - template: ./templates/app-build.yml
        parameters:
          platform: 'android'
  - job: "Build_iOS"
    timeoutInMinutes: 90
    pool:
      vmImage: macOS-12
    variables:
      - group: React Native Variables
      - group: device-authorization
      - name: lc.all
        value: 'en_US.UTF-8'
      - name: lang
        value: 'en_US.UTF-8'
    steps:
      - template: ./templates/app-build.yml
        parameters:
          platform: 'ios'
  - job: "Build_Storybook"
    timeoutInMinutes: 30
    pool:
      vmImage: macOS-12
    steps:
      - template: ./templates/storybook-build.yml
  - job: "Push_to_github"
    timeoutInMinutes: 30
    pool:
      vmImage: macOS-12
    variables:
      - group: github-authorization
    steps:
      - template: ./templates/push-repo-to-github.yml
        parameters:
          repository: 'amsterdam-app-frontend'
          sshKeySecureFile: 'frontend-github-ssh'
          sshPublicKey: $(sshPublicKeyFrontend)