trigger: none

pr: none

schedules:
  - cron: '0 0 * * 1'
    displayName: Monday certificates sync
    branches:
      include:
      - main

resources:
  repositories:
    - repository: aapp_app_ios-certificates
      type: git
      name: aapp_app_ios-certificates

jobs:
  - job: "Sync_iOS_certificates"
    timeoutInMinutes: 20
    pool:
      vmImage: macOS-13
    variables:
      - group: React Native Variables
      - group: device-authorization
      - name: lc.all
        value: 'en_US.UTF-8'
      - name: lang
        value: 'en_US.UTF-8'
    steps:
      - template: ./templates/ios-sync.yml