export enum RedirectEndpointName {
  getRedirectUrls = 'getRedirectUrls',
}

export enum RedirectKey {
  acknowledgeChild = 'acknowledgeChild',
  birth = 'birth',
  chatPrivacy = 'chatPrivacy',
  cityPassChildBudget = 'cityPassChildBudget',
  cityPassRequest = 'cityPassRequest',
  cityPassUsage = 'cityPassUsage',
  citypass = 'citypass',
  contactForm = 'contactForm',
  contactNewsletterSignup = 'contactNewsletterSignup',
  documents = 'documents',
  feedbackForm = 'feedbackForm',
  immigration = 'immigration',
  income_help = 'income_help',
  lifelessBirth = 'lifelessBirth',
  makeAppointMentWeesp = 'makeAppointMentWeesp',
  marriage = 'marriage',
  marriagePermission = 'marriagePermission',
  naturalisation = 'naturalisation',
  parking = 'parking',
  parking_request_license_plate = 'parking_request_license_plate',
  parking_visitors = 'parking_visitors',
  passing = 'passing',
  passingForFuneralDirectors = 'passingForFuneralDirectors',
  relocation = 'relocation',
}
