import {
  type AlertsRecord,
  AlertVariant,
} from '@/components/ui/feedback/alert/Alert.types'
import {getFirstMonthOfNextQuarter} from '@/modules/parking/utils/getFirstMonthOfNextQuarter'

export const alerts = {
  accountPinCodeChangeSuccess: {
    variant: AlertVariant.positive,
    title: 'Uw pincode is gewijzigd.',
    hasIcon: true,
    hasCloseIcon: true,
    testID: 'ParkingAccountPinCodeChangeSuccessAlert',
  },
  adjustSessionSuccess: {
    variant: AlertVariant.positive,
    title: 'Uw parkeersessie is aangepast',
    hasCloseIcon: true,
    hasIcon: true,
    testID: 'ParkingAdjustSessionSuccessAlert',
  },
  adjustTimeBalanceFailed: {
    variant: AlertVariant.negative,
    text: 'We konden het tijdsaldo niet aanpassen.',
    title: 'Mislukt',
    hasIcon: true,
    testID: 'ParkingManageVisitorAdjustTimeBalanceFailedAlert',
  },
  adjustTimeBalanceSuccess: {
    variant: AlertVariant.positive,
    text: 'Tijdsaldo is aangepast.',
    title: 'Gelukt',
    hasIcon: true,
    testID: 'ParkingManageVisitorAdjustTimeBalanceSuccessAlert',
  },
  createVisitorAccountSuccess: {
    variant: AlertVariant.positive,
    text: 'Voeg tijdsaldo toe en deel de meldcode en pincode met uw bezoek.',
    title: 'Nieuw bezoekersaccount',
    hasIcon: true,
    testID: 'ParkingManageVisitorCreateAccountSuccessAlert',
  },
  createVisitorAccountFailed: {
    variant: AlertVariant.negative,
    text: 'Er is iets misgegaan. Probeer het later nog een keer.',
    title: 'Geen bezoekersaccount',
    hasIcon: true,
    testID: 'ParkingManageVisitorCreateAccountFailedAlert',
  },
  decreaseTimeBalanceSuccess: {
    variant: AlertVariant.positive,
    text: 'Tijdsaldo is succesvol verlaagd.',
    title: 'Gelukt',
    hasIcon: true,
    testID: 'ParkingManageVisitorDecreaseTimeBalanceSuccessAlert',
  },
  decreaseTimeBalanceFailed: {
    variant: AlertVariant.negative,
    text: 'Tijdsaldo verlagen is mislukt, probeer het nog een keer.',
    title: 'Mislukt',
    hasIcon: true,
    testID: 'ParkingManageVisitorDecreaseTimeBalanceFailedAlert',
  },
  freeParkingSuccess: {
    variant: AlertVariant.positive,
    text: 'U hoeft geen parkeersessie te starten.',
    title: 'Parkeren in deze periode is gratis',
    hasIcon: true,
    testID: 'ParkingFreeParkingSuccessAlert',
  },
  inactiveSessionFailed: {
    variant: AlertVariant.negative,
    text: 'Uw sessie is verlopen. Plan een nieuwe sessie.',
    title: 'Sessie verlopen',
    hasIcon: true,
    testID: 'ParkingInactiveSessionFailedAlert',
  },
  increaseBalanceSuccess: {
    variant: AlertVariant.positive,
    text: 'Geldsaldo is verhoogd. Het kan even duren voordat het saldo is bijgewerkt.',
    title: 'Gelukt',
    hasIcon: true,
    hasCloseIcon: true,
    testID: 'ParkingIncreaseBalanceSuccessAlert',
  },
  increaseBalanceFailed: {
    variant: AlertVariant.negative,
    text: 'Geldsaldo verhogen is mislukt, probeer het nog een keer.',
    title: 'Mislukt',
    hasIcon: true,
    hasCloseIcon: true,
    testID: 'ParkingIncreaseBalanceFailedAlert',
  },
  insufficientMoneyBalanceFailed: {
    variant: AlertVariant.negative,
    text: 'Te weinig geld om parkeersessie te starten.',
    title: 'Niet genoeg geldsaldo',
    hasIcon: true,
    hasCloseIcon: false,
    testID: 'ParkingInsufficientMoneyBalanceFailedAlert',
  },
  insufficientMoneyBalance2Failed: {
    variant: AlertVariant.negative,
    text: 'Er is niet genoeg geldsaldo om te parkeren. Voeg eerst geld toe. Daarna kun kunt u de parkeersessie starten.',
    title: 'Uw saldo is te laag',
    hasIcon: true,
    hasCloseIcon: false,
    testID: 'ParkingInsufficientMoneyBalance2FailedAlert',
  },
  insufficientTimeBalanceFailed: {
    variant: AlertVariant.negative,
    text: `Op 1 ${getFirstMonthOfNextQuarter().format('MMMM')} ontvangt u nieuw tijdsaldo. Probeer eventueel een kortere parkeertijd te kiezen.`,
    title: 'Niet genoeg tijdsaldo',
    hasIcon: true,
    hasCloseIcon: false,
    testID: 'ParkingInsufficientTimeBalanceFailedAlert',
  },
  insufficientTimeBalanceVisitorFailed: {
    variant: AlertVariant.negative,
    text: 'Vraag aan de persoon die u bezoekt om het tijdsaldo te verhogen.',
    title: 'Niet genoeg tijdsaldo',
    hasIcon: true,
    hasCloseIcon: false,
    testID: 'ParkingInsufficientTimeBalanceFailedAlert',
  },
  loginForbiddenFailed: {
    variant: AlertVariant.negative,
    text: 'Controleer uw meldcode en pincode en probeer het opnieuw.',
    title: 'Inloggen mislukt',
    testID: 'ParkingLoginForbiddenFailedAlert',
  },
  loginFailed: {
    variant: AlertVariant.negative,
    text: 'Er is iets misgegaan. Probeer het opnieuw.',
    title: 'Inloggen mislukt',
    testID: 'ParkingLoginFailedAlert',
  },
  logoutWithAnotherAccountSuccess: {
    variant: AlertVariant.positive,
    text: 'U bent nog ingelogd met een ander account.',
    title: 'Uitgelogd',
    hasIcon: true,
    testID: 'ParkingLogoutWithAnotherAccountSuccessAlert',
  },
  maximumSessionsWarning: {
    variant: AlertVariant.warning,
    text: 'Pas de parkeertijd aan.',
    title: 'Maximum aantal parkeersessies bereikt',
    hasIcon: true,
    testID: 'ParkingMaximumSessionsWarningAlert',
  },
  saveLicensePlateDuplicateWarning: {
    variant: AlertVariant.warning,
    text: 'Dit kenteken is al opgeslagen in Mijn kentekens.',
    title: 'Kenteken bestaat al',
    hasIcon: true,
    hasCloseIcon: true,
    testID: 'ParkingLicensePlateDuplicateErrorAlert',
  },
  startSessionSuccess: {
    variant: AlertVariant.positive,
    title: 'Uw parkeersessie is opgeslagen',
    hasCloseIcon: true,
    hasIcon: true,
    testID: 'ParkingStartSessionSuccessAlert',
  },
  maintenanceInfo: {
    variant: AlertVariant.information,
    title: 'Onderhoud Parkeren',
    text: 'Op donderdag 13 november wordt Parkeren tijdelijk uitgeschakeld vanwege onderhoud. We doen ons best om dit zo snel mogelijk af te ronden. Dank voor uw geduld!',
    hasIcon: true,
    testID: 'ParkingMaintenanceAlert',
  },
} as const satisfies AlertsRecord

export type Alerts = keyof typeof alerts
