 name: Frontend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: src
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test, build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - run: yarn install --frozen-lockfile
      - run: yarn ${{ matrix.job }}